// <auto-generated />
namespace TasteFood.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ContextModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContextModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202403171353217_ContextModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
